### ISSUE TITLE
thread 'main' panicked at src/buffer.rs:236:45: range end index 5313296328 out of range for slice of length 4610561027

### ISSUE THREAD

**Issue by Rodrigodd** [ekiwi/fst-writer#2]
```
~/r/fst-writer main [101]> cargo run --example 2fst --release -- ~/repos/dmg-sim/dmgcpu/HDL/sm83/Icarus/dmg_waves3.fst out2.fst
    Finished `release` profile [optimized + debuginfo] target(s) in 0.45s
     Running `target/release/examples/2fst /home/rodrigodd/repos/dmg-sim/dmgcpu/HDL/sm83/Icarus/dmg_waves3.fst out2.fst`
thread 'main' panicked at src/buffer.rs:236:45:
range end index 5313296328 out of range for slice of length 4610561027
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
   2: core::slice::index::slice_end_index_len_fail_rt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/slice/index.rs:64:5
   3: core::slice::index::slice_end_index_len_fail
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/slice/index.rs:57:5
   4: <fst_writer::buffer::SingleVecLists as fst_writer::buffer::ValueLists>::extract_list
   5: fst_writer::buffer::SignalBuffer::finish::{{closure}}
             at ./src/buffer.rs:158:33
   6: fst_writer::io::write_value_changes
             at ./src/io.rs:422:20
   7: fst_writer::io::write_value_change_section
             at ./src/io.rs:494:5
   8: fst_writer::buffer::SignalBuffer::finish
             at ./src/buffer.rs:151:9
   9: fst_writer::writer::FstBodyWriter<W>::finish
             at ./src/writer.rs:125:24
  10: _2fst::main
             at ./examples/2fst.rs:65:5
  11: core::ops::function::FnOnce::call_once
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Input file:

[dmg_waves3.aa.zip](https://github.com/user-attachments/files/18190885/dmg_waves3.aa.zip)
[dmg_waves3.ab.zip](https://github.com/user-attachments/files/18190886/dmg_waves3.ab.zip)
[dmg_waves3.ac.zip](https://github.com/user-attachments/files/18190887/dmg_waves3.ac.zip)

I splitted the file to work around GitHub's file size limit. Concatenate the parts together before treating it as a zip:

```
cat dmg_waves3.aa.zip dmg_waves3.ab.zip dmg_waves3.ac.zip  > dmg_waves3.zip
```

**Comment by ekiwi** [comment]
Thanks! Excellent bug report, as always!

**Comment by ekiwi** [comment]
So what happens here is that the in-memory buffer fills up past 4 GiB, and I am sure that there is an `u32` being used as index somewhere.

The solution would be to add code to commit the value changes to the file occasionally, such that the buffer never actually fills up this much.

**Comment by ekiwi** [comment]
should be fixed on `main` now

**Comment by Rodrigodd** [comment]
The output now appears to be corrupted (original below, output of `2fst` above):

![image](https://github.com/user-attachments/assets/1dd15945-9293-4082-a220-0be549f809ed)

**Comment by ekiwi** [comment]
:cry:

**Comment by ekiwi** [comment]
Please try the latest `main`.

This is what the output looks like for me now:
![image](https://github.com/user-attachments/assets/ed4a5d87-cb27-4e92-a967-2ef83fe84674)

**Comment by Rodrigodd** [comment]
@ekiwi Tried again on master (commit bf5db00972240b5480528b2d3deb727f63eba475), and I am still getting the same behavior.

**Comment by ekiwi** [comment]
@Rodrigodd : I think I forgot to push my changes :facepalm:  ... sorry about that.
